apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: gremjua/query-service
---
apiVersion: v1
kind: Service
metadata:
    name: query-srv
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002  # port I want the k8s service to expose, so if I call localhost:4002 then it will redirect to the pod's port 5000
      targetPort: 5000  # port our flask app listens to
