[tool.poetry]
name = "posts"
version = "0.1.0"
description = ""
authors = ["Juan Gremes <juan.gremes@affirm.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
flask = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
